




CREATE DATABASE STORE;
USE STORE;
DROP TABLE PRODUCT;
CREATE TABLE PRODUCT(
	PRODUCT_ID bigint NOT NULL  PRIMARY KEY auto_increment,
    PRODUCT_NAME VARCHAR(50) NOT NULL UNIQUE,
    CATEGORYID BIGINT NOT NULL ,
    DESCRIPTION VARCHAR(100) ,
    TAGS VARCHAR(100) NOT NULL,
    IMAGEURL VARCHAR(300) NOT NULL,
    SUPPLIER_ID BIGINT NOT NULL,
    PIECES INT DEFAULT 0,
    PRICE INT DEFAULT 0
);

CREATE TABLE CATEGORY (
	CATEGORY_ID BIGINT NOT NULL primary key auto_increment,
    PARENT_ID BIGINT ,
    CATEGORY_NAME VARCHAR(40) UNIQUE NOT NULL,
    CATEGORY_DESC VARCHAR(100) ,
    IMAGE VARCHAR(1000) 
);

CREATE TABLE CUSTOMERS(
	CUSTOMER_ID BIGINT AUTO_INCREMENT ,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(150) NOT NULL ,
    ADDRESS VARCHAR(100),
    PHONE_NUMBER VARCHAR(15)  ,
    CREATED_AT DATE NOT NULL,
    CONSTRAINT CUSTOMER_PK PRIMARY KEY(CUSTOMER_ID)
);

CREATE TABLE SUPPLIERS (
	SUPPLIER_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL UNIQUE,
    CONTACT VARCHAR(11) NOT NULL UNIQUE,
    ADDRESS VARCHAR(100) NOT NULL,
    CITY VARCHAR(20),
    POSTALCODE INT ,
    COUNTRY VARCHAR(20) NOT NULL
    
);
CREATE TABLE SHIPPERS (
	SHIPPER_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL UNIQUE,
    CONTACT VARCHAR(11) NOT NULL,
    COUNTRY VARCHAR(20) NOT NULL
);

CREATE TABLE ADMINISTRATOR (
	EMAIL VARCHAR(30) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR(130) NOT NULL , 
    CREATED_AT DATE  NOT NULL,
    ROLE ENUM('ADMIN' , 'MANAGER' , 'ACCOUNTANT') NOT NULL
);


DROP TABLE ORDERDETAILS;

CREATE TABLE ORDERDETAILS(
	ORDER_ID BIGINT NOT NULL,
    AMOUNT INT NOT NULL,
    CUSTOMERID BIGINT NOT NULL,
    STATUS ENUM('DELIVERED' , 'PENDING',  'CONFIRMED' , 'DISPATCHED' , 'CANCELLED'),
    DELIVERY_PARTNER BIGINT,  
    ADDRESS VARCHAR(100),
    PRIMARY KEY (ORDER_ID)
    
);
USE STORE;
DROP TABLE TRANSACTIONS;
CREATE TABLE TRANSACTIONS (
	TRANSACTION_ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL ,
	AMOUNT INT NOT NULL,
    ORDER_ID BIGINT NOT NULL,
    PAYMENT_METHOD VARCHAR(10) NOT NULL,
    TRANSACTION_AT DATE NOT NULL,
    CARD_NUMBER BIGINT NOT NULL,
    CARD_PIN INT NOT NULL,
    CARD_EXPIRY_DATE DATE NOT NULL,
    PRIMARY KEY(TRANSACTION_ID)
);


CREATE TABLE ORDERS_ITEMS(
	ORDER_ITEMS_ID BIGINT PRIMARY KEY,
	ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL , 
    QUANTITY INT DEFAULT 0
);
SELECT * FROM ORDERDETAILS;
DELETE FROM ORDERDETAILS WHERE ORDER_ID = 1;
SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE ORDERDETAILS ADD CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMERS(CUSTOMER_ID);
ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY(CATEGORYID) REFERENCES CATEGORY(CATEGORY_ID);
ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_supplier FOREIGN KEY(SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID);
ALTER TABLE ORDERDETAILS ADD CONSTRAINT FK_ORDERDETAILS_SHIPPER FOREIGN KEY(DELIVERY_PARTNER) REFERENCES SHIPPERS(SHIPPER_ID);
ALTER TABLE ORDERDETAILS ADD CONSTRAINT FK_ORDERDETAILS_SHIPPERS FOREIGN KEY (SHIPPER_ID) REFERENCES SHIPPERS(SHIPPER_ID);
ALTER TABLE TRANSACTIONS ADD CONSTRAINT FK_TRANSACTIONS_CUSTOMER FOREIGN KEY(USER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID);
ALTER TABLE TRANSACTIONS ADD CONSTRAINT FK_TRANSACTIONS_ORDERS FOREIGN KEY(ORDER_ID) REFERENCES ORDERDETAILS(ORDER_ID);
ALTER TABLE CATEGORY ADD CONSTRAINT FK_CATEGORY_CATEGORY FOREIGN KEY(PARENT_ID) REFERENCES CATEGORY(CATEGORY_ID);
ALTER TABLE ORDERS_ITEMS ADD CONSTRAINT FK_ITEMS_ORDERS FOREIGN KEY(ORDER_ID) REFERENCES ORDERDETAILS(ORDER_ID);
ALTER TABLE ORDERS_ITEMS ADD CONSTRAINT FK_ITEMS_PRODUCTS FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);


ALTER TABLE PRODUCT ADD COLUMN ENCODED_ID VARCHAR(20);
alter table ORDERDETAILS drop constraint FK_ORDERDETAILS_SHIPPERS;
ALTER TABLE SHIPPERS;
DROP TABLE SUPPLIERS;



-- TESTS 


INSERT INTO CUSTOMERS VALUES(113,'HAMZA' , 'USMANI', 'TALHAusmani021@gmail.com' , 'password' , 'saima jinnah avenue , malir , karachi' , '03322411710' , '2015-11-11');
INSERT INTO ADMINISTRATOR VALUES('HAMZAUSMANI302@gmail.com' , 'hello123' , '2020-10-13' , 'MANAGER' );
INSERT INTO ORDERDETAILS VALUES(111, 112);
INSERT INTO ORDERDETAILS VALUES(112 ,113);
INSERT INTO ORDERDETAILS VALUES(112,2000,113 , 'PENDING' , NULL);
UPDATE ORDERDETAILS SET STATUS='CANCELLEd' WHERE ORDER_ID = 112;
SELECT * FROM ORDERDETAILS;
-- DISCARDING CART FOR NOW
